### ISSUE TITLE
Windows 81. Enterprise trial url changed

### ISSUE THREAD

**Issue by MarkDarwin** [Tiberriver256/Auto-Microsoft-Deployment-Toolkit-Installation-and-Scaffolding#1]
It looks like the url for this download has changed.  I have found this line which works right now:

URI = 'http://care.dlservice.microsoft.com/dl/download/5/3/C/53C31ED0-886C-4F81-9A38-F58CE4CE71E8/9200.16384.WIN8_RTM.120725-1247_X64FRE_ENTERPRISE_EVAL_EN-US-HRM_CENA_X64FREE_EN-US_DV5.ISO'
        DestinationPath = "$ISOPath\Win81EnterpriseTrialx64.iso"

This was the original line:
URI = "http://download.microsoft.com/download/B/9/9/B999286E-0A47-406D-8B3D-5B5AD7373A4A/9600.16384.WINBLUE_RTM.130821-1623_X64FRE_ENTERPRISE_EVAL_EN-US-IRM_CENA_X64FREE_EN-US_DV5.ISO"

(Thanks for sharing your code, it's helping me learn a lot.)

**Comment by Tiberriver256** [comment]
Thanks for the heads up. I fixed the link. Glad it was useful for you. I more advanced work in my MDTBuilder repository if you are interested in more.
https://github.com/Tiberriver256/MDTBuilder

**Comment by MarkDarwin** [comment]
Thanks, wish I had seen this other repo as I've been updating your old one internally and was going to suggest some changes.  I'll fork the new one instead to play with.

_Nice code by the way._
